name: Continuos Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: ./aplicacao
      run: docker-compose up -d --build

  test:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Reset database and seed
        working-directory: ./aplicacao
        run: docker-compose run app rails db:reset
      - name: Run test
        working-directory: ./aplicacao
        run: docker-compose run app rspec
